### ISSUE TITLE
Error Inflate Exception FloatingActionButton on API 19

### ISSUE THREAD

**Issue by aadilmehrajbhat** [robertlevonyan/customFloatingActionButton#16]
On Kitkat API 19, I get InflateException, but on API >= 21 it work fine.

Stack trace:

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.aadilmehraj.android.accrual/com.aadilmehraj.android.accrual.EditorActivity}: android.view.InflateException: Binary XML file line #69: Error inflating class com.robertlevonyan.views.customfloatingactionbutton.FloatingActionButton
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2338)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
        at android.app.ActivityThread.access$800(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:5292)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.view.InflateException: Binary XML file line #69: Error inflating class com.robertlevonyan.views.customfloatingactionbutton.FloatingActionButton
        at android.view.LayoutInflater.createView(LayoutInflater.java:620)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
        at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:303)
        at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:284)
        at com.aadilmehraj.android.accrual.EditorActivity.onCreate(EditorActivity.java:87)
        at android.app.Activity.performCreate(Activity.java:5292)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390) 
        at android.app.ActivityThread.access$800(ActivityThread.java:151) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321) 
        at android.os.Handler.dispatchMessage(Handler.java:110) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:5292) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.constructNative(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at android.view.LayoutInflater.createView(LayoutInflater.java:594)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
        at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:303) 
        at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:284) 
        at com.aadilmehraj.android.accrual.EditorActivity.onCreate(EditorActivity.java:87) 
        at android.app.Activity.performCreate(Activity.java:5292) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390) 
        at android.app.ActivityThread.access$800(ActivityThread.java:151) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321) 
        at android.os.Handler.dispatchMessage(Handler.java:110) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:5292) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_camera.xml from drawable resource ID #0x7f0800a3
        at android.content.res.Resources.loadDrawable(Resources.java:2152)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
        at com.robertlevonyan.views.customfloatingactionbutton.FloatingActionButton.initTypedArray(FloatingActionButton.java:77)
        at com.robertlevonyan.views.customfloatingactionbutton.FloatingActionButton.<init>(FloatingActionButton.java:63)
        at com.robertlevonyan.views.customfloatingactionbutton.FloatingActionButton.<init>(FloatingActionButton.java:57)
        at java.lang.reflect.Constructor.constructNative(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:594) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
        at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:303) 
        at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:284) 
        at com.aadilmehraj.android.accrual.EditorActivity.onCreate(EditorActivity.java:87) 
        at android.app.Activity.performCreate(Activity.java:5292) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390) 
        at android.app.ActivityThread.access$800(ActivityThread.java:151) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321) 
        at android.os.Handler.dispatchMessage(Handler.java:110) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:5292) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
        at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
        at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
        at android.content.res.Resources.loadDrawable(Resources.java:2148)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:602) 
        at com.robertlevonyan.views.customfloatingactionbutton.FloatingActionButton.initTypedArray(FloatingActionButton.java:77) 
        at com.robertlevonyan.views.customfloatingactionbutton.FloatingActionButton.<init>(FloatingActionButton.java:63) 
        at com.robertlevonyan.views.customfloatingactionbutton.FloatingActionButton.<init>(FloatingActionButton.java:57) 
        at java.lang.reflect.Constructor.constructNative(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:594) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
        at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:303) 
        at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:284) 
        at com.aadilmehraj.android.accrual.EditorActivity.onCreate(EditorActivity.java:87) 
        at android.app.Activity.performCreate(Activity.java:5292) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390) 
        at android.app.ActivityThread.access$800(ActivityThread.java:151) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321) 
        at android.os.Handler.dispatchMessage(Handler.java:110) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:5292) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640) 
        at dalvik.system.NativeStart.main(Native Method) 

In my app level build.gradle file I have enabled
`vectorDrawables.useSupportLibrary = true`

also in my EditorActivity I have enabled
`static {
        AppCompatDelegate.setCompatVectorFromResourcesEnabled(true);
    }`

I am using vector drawable, maybe it is concerned with **app:srcCompat**

**Comment by robertlevonyan** [comment]
for setting the icon us app:fabIcon
